version: "3.9"

services:
  web:
    build: .
    command: gunicorn safe.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=safe.settings
      - DEBUG=False
      - SECRET_KEY=admin88asilbek88
      - DB_NAME=safe_clinic
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: safe_clinic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
