version: "3.9"
services:
  web:
    build: .
    command: gunicorn safe.wsgi:application --bind 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=safe.settings
      - DATABASE_URL=postgresql://admin:admin123@db:5432/safe_clinic
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: safe_clinic
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
