# Generated by Django 5.2 on 2025-07-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_created_at_alter_service_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(),
        ),
    ]
