# Generated by Django 5.2 on 2025-07-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_duration_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='Длительность (мин)'),
        ),
    ]
