# Generated by Django 5.2 on 2025-07-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='service_photos/', verbose_name='Фото'),
        ),
    ]
