# Generated by Django 4.2.3 on 2025-08-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctor_photos/')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tags', models.CharField(choices=[('implant_surgeon', 'Хирург-имплантолог'), ('dentist', 'Стоматолог'), ('radiologist', 'Рентгенолог'), ('pediatrician', 'Педиатр'), ('orthopedic_surgeon', 'Хирург-ортопед'), ('surgeon', 'Хирург')], max_length=30)),
                ('clients', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10)),
            ],
        ),
    ]
