# Generated by Django 5.2.4 on 2025-07-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(default='Не указан', max_length=255)),
                ('tags', models.CharField(choices=[('director', 'Директор'), ('administrator', 'Администратор'), ('dentist', 'Стоматолог'), ('radiologist', 'Рентгенолог'), ('pediatrician', 'Педиатр'), ('surgeon', 'Хирург'), ('patient', 'Пациент')], max_length=20)),
                ('clients', models.TextField(blank=True)),
            ],
        ),
    ]
