# Generated by Django 5.2.4 on 2025-07-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listdoctors', '0002_doctor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tags',
            field=models.CharField(choices=[('implant_surgeon', 'Хирург-имплантолог'), ('dentist', 'Стоматолог'), ('radiologist', 'Рентгенолог'), ('pediatrician', 'Педиатр'), ('orthopedic_surgeon', 'Хирург-ортопед'), ('surgeon', 'Хирург')], max_length=30),
        ),
    ]
