# Generated by Django 5.2 on 2025-07-16 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('doctor', 'Врач'), ('patient', 'Пациент'), ('director', 'Директор'), ('dentist', 'Стоматолог'), ('radiologist', 'Рентгенолог'), ('paediatrician', 'Педиатр'), ('surgeon', 'Хирург')], max_length=50),
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('confirmation_code', models.CharField(max_length=6)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('code_created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
