# Generated by Django 4.2.3 on 2025-08-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='code_created_at',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='confirmation_code',
        ),
    ]
