# Generated by Django 5.2 on 2025-07-19 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('doctor', 'Врач'), ('director', 'Директор'), ('dentist', 'Стоматолог'), ('radiologist', 'Рентгенолог'), ('paediatrician', 'Педиатр'), ('surgeon', 'Хирург'), ('patient', 'Пациент')], max_length=50),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название филиала')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email филиала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='branch_photos/', verbose_name='Фото филиала')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_branches', to=settings.AUTH_USER_MODEL, verbose_name='Директор филиала')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
    ]
