# Generated by Django 4.2.3 on 2025-07-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('admin', 'Администратор'), ('doctor', 'Врач'), ('director', 'Директор'), ('dentist', 'Стоматолог'), ('radiologist', 'Рентгенолог'), ('paediatrician', 'Педиатр'), ('surgeon', 'Хирург'), ('patient', 'Пациент')], max_length=100, verbose_name='Роль'),
        ),
    ]
