# Generated by Django 4.2.3 on 2025-08-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listpatients', '0001_initial'),
        ('listdoctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_slot', models.CharField(choices=[('08:00-09:00', '08:00-09:00'), ('09:00-10:00', '09:00-10:00'), ('10:00-11:00', '10:00-11:00'), ('11:00-12:00', '11:00-12:00'), ('12:00-13:00', '12:00-13:00'), ('13:00-14:00', '13:00-14:00'), ('14:00-15:00', '14:00-15:00'), ('15:00-16:00', '15:00-16:00'), ('16:00-17:00', '16:00-17:00'), ('17:00-18:00', '17:00-18:00')], max_length=20, verbose_name='Временной слот')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_appointments', to='listdoctors.doctor', verbose_name='Доктор')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_appointments', to='listpatients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Запись на приём',
                'verbose_name_plural': 'Записи на приём',
                'unique_together': {('doctor', 'date', 'time_slot')},
            },
        ),
    ]
