# Generated by Django 5.2 on 2025-07-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
    ]
